### ISSUE TITLE
Icon not visualized since last update.

### ISSUE THREAD

**Issue by SeLLeRoNe** [vigonotion/hass-simpleicons#10]
Hi there,
I am facing an odd issue from latest update, the icon I was using for VS Code disappeared :)

![image](https://user-images.githubusercontent.com/9599441/81605096-4008fc00-93d1-11ea-9df4-5d6160acd1ae.png)

This is the part of config where I was loading it:
```  icon: si:visualstudiocode
```

is there something I have missed in the latest release that would explain this?

Thanks
Andrea

**Comment by vigonotion** [comment]
What version of Home Assistant and this integration are you using? I pushed an update for HA 0.110, which will change the way icons will load, but it shouldn't be possible to install on 0.109

**Comment by SeLLeRoNe** [comment]
HA: 0.109.6
integration: 1.1.0

**Comment by allan-reynolds** [comment]
Same icon missing issues here.  
Home Assistant 0.109.4
integration: 1.1.0 installed and updated via HACS (0.24.4)

**Comment by kdoh82** [comment]
my icon disappeared as well. happened after i upgraded the 1.1.0. on HA 0.109.6. downgrading back to 1.0.3 fixed the issue.

**Comment by vigonotion** [comment]
Please **downgrade to v1.0.3** and only update when you are on Home Assistant version 0.110.

There is a bug in HACS, you shouldn't have been able to install the new version yet.

**Comment by vigonotion** [comment]
The version check has been fixed in HACS 0.24.5, so please update that and you should be save (v1.1.0 will be blocked until you update to HA 0.110.0b0 or higher)
