### ISSUE TITLE
New icons uploaded to the page do not load.

### ISSUE THREAD

**Issue by jonathanathe** [vigonotion/hass-simpleicons#108]
Good morning,

I would like to know how I can do it, because there is a new icon uploaded in SimpleIcons and I can't put it in home assistant. How can I do it? Thank you.

Regards.

**Comment by vigonotion** [comment]
Is your icon already released? I have to release a new version of this integration, then you can update and use the icon.

**Comment by vigonotion** [comment]
Please update to version v1.16.0 and try again

**Comment by jonathanathe** [comment]
Hello, I have already updated and it still does not appear, this is the one I am showing you now in the image.

imou.svg

![image](https://user-images.githubusercontent.com/34164094/115712451-13958800-a375-11eb-85b8-dce80acbf874.png)

**Comment by jonathanathe** [comment]
Please @vigonotion can you help me. Thank you,

**Comment by vigonotion** [comment]
Your icon has been released in SI v4.20.0 (see here: https://github.com/simple-icons/simple-icons/pull/5479)
That version was not yet available when you wrote the issue. Please update the integration to 1.17, it should be working then

**Comment by jonathanathe** [comment]
Hello @vigonotion , I don't understand why you won't let me install it, I don't know what version of home assistant you're talking about.![Screenshot_2021-04-30-13-09-48-060_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/34164094/116687427-73afae00-a9b5-11eb-85a3-390585b5d576.jpg)

**Comment by vigonotion** [comment]
Please select the v1.17 version as I wrote in the comment above.

The 1.18 version is for the next Home Assistant version, normally you shouldn't be able to see that version

**Comment by jonathanathe** [comment]
Good morning @vigonotion, it did not allow me to update to any version or to the previous ones until I updated to the version that appeared in the previous image that I sent you and now that I update I can install the version that he told me but within the integrations it no longer appears to add it so it no longer lets me see any icon 

![Screenshot_2021-05-01-09-56-56-497_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/34164094/116775581-fabb5f80-aa63-11eb-99af-aed64833e800.jpg)

**Comment by jonathanathe** [comment]
Good morning @vigonotion,

This is already solved with the solution of the ticket you opened here @drthanwho #112. Thank you for your help.

Regards.
