### ISSUE TITLE
Icons not visualizing including HACS icon

### ISSUE THREAD

**Issue by sheminasalam** [vigonotion/hass-simpleicons#15]
I am running Home Assistant 0.110.4 on Rpi4. I have tried simpleicons v1.1.0 but the icons are not visualizing. i also realized that when simpleicons is installed, the HACS icon in the side bar is also not visualized. But when i remove the simpleicons integration and also the installation in HACS,  the HACs icon reappears and works normal.

**Comment by vigonotion** [comment]
I need some more information from you:

- did you restart Home Assistant after installing simple-icons?
- What version of HACS are you running?
- How are you trying to use the icons? (Which icon did you try, how did you prefix it)
- did you reload without cache?
- which browser did you use?

Also, please add the log output from
- Home Assistant
- the web console

And if you can, check in the Network tab if `si.js` is correctly loaded.

That's it, tell me if you need help, I just need somewhere to start as it works fine for me

**Comment by sheminasalam** [comment]
1. I did as in the documentation i,e installed it and restart HA, after which i checked integrations page for simpleicons but it was not there. So i tried rebooting the host after which i saw it in integrations page in settings. I added it as said.Then I tried it with one of my switches and it worked for some time but soon it stopped visualizing icons. I am having so much inconsistency. so its difficult to explain all the issues. I have also noticed that when I changed the icon in configure, icon appears but with refresh it goes.

2. Integration version: | 1.0.3

3. si:facebook, si:broadcom

4. I did shift+f5 in chrome

5. chrome

there is nothing in relavent in HA logs
.
web console
BROWSER_MOD 1.0.2 IS INSTALLED    DeviceID: b55af8fe-614f5bbd
:8123/hacsfiles/lovelace-template-entity-row/template-entity-row.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
layout-card.js:68 LAYOUT-CARD 1.2.1 IS INSTALLED 
load_resource.ts:1 Uncaught (in promise) http://192.168.33.250:8123/hacsfiles/lovelace-template-entity-row/template-entity-row.js
custom-header.js:596   CUSTOM-HEADER    Version 1.4.7  
button-card.js:1597   BUTTON-CARD   Version 3.3.5 
0:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
custom-header.js:596 Device ID:  b55af8fe-614f5bbd
:8123/hassio:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
:8123/developer-tools/info:1 [Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions specified. Specifying dimensions improves performance. See https://crbug.com/954323
:8123/hassio:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
leaflet140_patched_tileLayer.v14.js:5 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://embed.windy.com/v/19.10.3.emb.985a/iconfont.woff
embed2.html?lat=15.687&lon=79.475&zoom=4&level=surface&overlay=wind&menu=calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=8.764&detailLon=77.480&metricWind=default&metricTemp=default&radarRange=-1:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
```

**Comment by sheminasalam** [comment]
this is the web console log when the icons were visualized 

```
BROWSER_MOD 1.0.2 IS INSTALLED    DeviceID: b55af8fe-614f5bbd
layout-card.js:68 LAYOUT-CARD 1.2.1 IS INSTALLED 
:8123/hacsfiles/lovelace-template-entity-row/template-entity-row.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
custom-header.js:596   CUSTOM-HEADER    Version 1.4.7  
load_resource.ts:1 Uncaught (in promise) http://192.168.33.250:8123/hacsfiles/lovelace-template-entity-row/template-entity-row.js
button-card.js:1597   BUTTON-CARD   Version 3.3.5 
custom-header.js:596 Device ID:  b55af8fe-614f5bbd
0:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
iron-selection.js:13 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://192.168.33.250:8123/static/fonts/roboto/Roboto-Bold.woff2
leaflet140_patched_tileLayer.v14.js:5 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://embed.windy.com/v/19.10.3.emb.985a/iconfont.woff
embed2.html?lat=15.687&lon=79.475&zoom=4&level=surface&overlay=wind&menu=calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=8.764&detailLon=77.480&metricWind=default&metricTemp=default&radarRange=-1:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
```

**Comment by vigonotion** [comment]
Logs look good. Please go onto the networks tab (in the same window as JS console) and check if si.js is loaded on page load (should give a 200)

**Comment by sheminasalam** [comment]
I have checked, It gives 200. I have seen one more thing. When I take configure UI in dashboard and try to edit the entity card, the logo appears in the preview window and afterwards also in the dashboard. I have also checked this with other browsers and devices, In all I am having the same issue. but now i dont see that the HACS icon in the side bar is not getting affected.

**Comment by NEPP90** [comment]
Hi! I'm new on HA.
I have installed this with HACS and I'm also having the same problem, the icons don't appear.

**Comment by sheminasalam** [comment]
> Hi! I'm new on HA.
> I have installed this with HACS and I'm also having the same problem, the icons don't appear.

did you reload without cache?

**Comment by vigonotion** [comment]
@sheminasalam can you also share your lovelace config? Just the part where you try to add the icons

**Comment by vigonotion** [comment]
@NEPP90 @sheminasalam can you please try the Home Assistant dev version? Tomorrow a HA 0.111 should be available if you can't setup a dev environment, but keep in mind it's beta and probably not a good idea to use in production.

I tried with the newest dev in various ways, chrome and firefox and I can't reproduce the bug, I get the icons every time

**Comment by sheminasalam** [comment]
i think that I will wait for a stable version and would let you know.

**Comment by NEPP90** [comment]
> 
> 
> > Hi! I'm new on HA.
> > I have installed this with HACS and I'm also having the same problem, the icons don't appear.
> 
> did you reload without cache?

Thanks! That was the problem. Sorry for waste your time with that.
Thanks to all!

**Comment by sheminasalam** [comment]
I have some other addons installed such as custom header, layout card, fontawesome . Can these be affecting this addon. I have seen that such issues are there.

**Comment by sheminasalam** [comment]
@vigonotion I have seen that the problem appears with all the custom icons addons. So all these must be conflicting with some other addons as I mentioned above. i had a similar issue with slide addon and custom header addon. can you check it.

**Comment by NovaGL** [comment]
Custom Icons doesn't work with 0.110.0 and above due to changes the way icons are displayed.

Simple Icons is still working for me though. I think you shouldn't mix plugins and only discuss Simple Icons in this issue to avoid confusion.

**Comment by sheminasalam** [comment]
@NovaGL just giving a heads up, it might help improve this work.

**Comment by vigonotion** [comment]
@NovaGL thanks, but custom icons do work in HA > 0.110, they just changed the way how custom icon sets need to be loaded (see https://developers.home-assistant.io/blog/2020/05/09/custom-iconsets). I don't know about the other icon sets, but I updated hass-simpleicons according to that blog post and they should work in 0.110 (and work for me)

**Comment by NovaGL** [comment]
@vigonotion should have been more clear the hacs  add-on custom icons don't work.

All I was suggesting is problems with other iconsets should be discussed in the relevant repo

**Comment by sheminasalam** [comment]
In the latest release, I dont think that I have this problem. I think it has been rectified. I appreciate the good work
