### ISSUE TITLE
Can't use si icons for views?

### ISSUE THREAD

**Issue by JeeCee1** [vigonotion/hass-simpleicons#157]
Hi Tom, schöne Grüße aus Berlin von ein Holländer ;)

Thanks for your awesome project!

Am I doing something wrong or can this component not be used for the icons of views?

**Comment by drinfernoo** [comment]
They work for me, currently running HA 2021.11.0.

**Comment by vigonotion** [comment]
Can you please test the v2 beta and add a comment if it works for you here: https://github.com/vigonotion/hass-simpleicons/discussions/194 ?

It should work for views, there is no difference between lovelace or other views in HA icon-wise

**Comment by ildar170975** [comment]
v2.0.0-rc.1
2021.11.3
works in Win10x64 + Chrome  95.0.4638.69 + Firefox 94

**Comment by vigonotion** [comment]
V2 has been released:
Please try version 2 and open another issue id the issue still persists: https://github.com/vigonotion/hass-simpleicons/releases/tag/v2.0.0
