### ISSUE TITLE
[Request] Implement icon picker support

### ISSUE THREAD

**Issue by drinfernoo** [vigonotion/hass-simpleicons#192]
It would be great if these icons could be added to the HA icon picker!

Details on the code changes and implementation here: https://github.com/home-assistant/frontend/pull/10399

**Comment by vigonotion** [comment]
Can you please test the v2 beta and add a comment if it works for you here: https://github.com/vigonotion/hass-simpleicons/discussions/194 ?

**Comment by NemesisRE** [comment]
v2-rc1 seems  to work 👍

**Comment by drinfernoo** [comment]
@NemesisRE Clear your browser cache.

**Comment by NemesisRE** [comment]
Works like a charm 😅

**Comment by vigonotion** [comment]
V2 has officially been released
