### ISSUE TITLE
Icons dont working

### ISSUE THREAD

**Issue by milandzuris** [vigonotion/hass-simpleicons#223]
![image](https://user-images.githubusercontent.com/42905545/153766506-b3bc91d8-cc53-4590-b3e6-a028de5af077.png)
Hi, icons don't work or am I doing something wrong?

**Comment by xeospeed** [comment]
They don't seem to be working for me, either.

**Comment by WalterWampe** [comment]
bump

**Comment by vigonotion** [comment]
@xeospeed @WalterWampe @milandzuris 
Please try version 2 and open another issue id the issue still persists: https://github.com/vigonotion/hass-simpleicons/releases/tag/v2.0.0
