### ISSUE TITLE
Icons not loading when casting

### ISSUE THREAD

**Issue by Fabenissimo** [vigonotion/hass-simpleicons#236]
Hello,

when I try to cast my Lovelace Dashboard to my Google Nest Hub the si-icons don't load.
I tried restarting HA and my Google Nest Hub (multiple times), but the Icons still don't load once the casting starts. If I'm using my PC/Mobile Phone the icons load wihout any issues. 

I tried with both the latest release and the 2.0 rc.

I didn't find any other issues relating to casting. I hope I've provided you with enough information. If you need any more info, let me know.

Fabian

**Comment by vigonotion** [comment]
Can you try using font awesome icons or other custom icon packs for HA? I don't have a google cast device to test and I'm not sure how to debug the issue
