### ISSUE TITLE
Are all icons loaded each time site is refreshed

### ISSUE THREAD

**Issue by agneevX** [vigonotion/hass-simpleicons#24]
Hello,

I have a question. Are all icons reloaded when the front end is refreshed or just the ones in use?

**Comment by vigonotion** [comment]
Currently the whole simple icons icon set is loaded on page load. This can be improved in two ways:
1. Send a 304 Unchanged for the icon set (easy)
2. Only send the icons actually needed to the frontend (will take more time, but totally possible thanks to the new HA icon loading logic)

I might find some time to do the 304 response in the next days, then the icon set should only be loaded once until a new version is released. 

The chunk loading is something I want to do but I currently don't have time for that (PRs are welcome)

**Comment by agneevX** [comment]
Any update on this @vigonotion? Thanks!

**Comment by IIAIronWolf** [comment]
Has this been updated? This seems like an unnecessary load on the HA server.

**Comment by agneevX** [comment]
> This seems like an unnecessary load on the HA server.

**Comment by vigonotion** [comment]
V2 has been released with lazy loading support: https://github.com/vigonotion/hass-simpleicons/releases/tag/v2.0.0
