### ISSUE TITLE
Not working properly after the lastest HA updates

### ISSUE THREAD

**Issue by CharlesGitHib** [vigonotion/hass-simpleicons#241]
The icons don't show up after the latest HA Update. Could you please check. Thanks.

**Comment by vigonotion** [comment]
It's working for me. Can you please provide some more information:

- Exact HA Version
- simpleicons component version
- Browser/App you are using to access HA

**Comment by CharlesGitHib** [comment]
Don't worry, it's working fine with Edge, Chrome, Opera, Silk(under alexa) and Firefox. I was running it as an app using Chrome extension and there is when the problem occurs.

**Comment by digitalMedic** [comment]
The icons do not show up for me.  I have removed and reinstalled the integration under HACS and still no icons.

Home Assistant 2023.4.1
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230406.1 - latest

SI version 2.2.0

**Comment by vigonotion** [comment]
please try the newest si version and the newest home assistant version and open a new issue if you still have problems
