### ISSUE TITLE
Missing icon(s?)

### ISSUE THREAD

**Issue by FunkeyFlo** [vigonotion/hass-simpleicons#243]
[This icon](https://simpleicons.org/?q=F1) is not available through the integration. This is the first icon I've run into that doesn't seem to be available. Am I missing something?

**Comment by vigonotion** [comment]
Maybe it is a new icon, then I'll have to release a new version.

Can you please post a screenshot of what you tried? And please try some other icons and see if they work (like `si:google`).
Also, did you restart Home Assistant after installing the integration?

**Comment by vigonotion** [comment]
Oh sorry, overread that this is the first icon that's NOT available. Gonna make an update with the new icons later today

**Comment by vigonotion** [comment]
It should work in the newest version!
