### ISSUE TITLE
Icons not visible

### ISSUE THREAD

**Issue by TheSgrash** [vigonotion/hass-simpleicons#245]
I just installed the custom integration via HACS on my HA Core 2023.1

I'm not able to use it as `si:` is not resolved and so icons are not shown

Is there any missing piece in configuration instructions?

**Comment by ScapSie** [comment]
Didn't show up using webbrowser Firefox (preferred). 
Tried using webrowser Edge, icons are there!
Hope this is helpful!

**Comment by TheSgrash** [comment]
@ScapSie I'm using Chrome on Mac

**Comment by vigonotion** [comment]
Did you restart HA after installing?
Maybe try reloading without cache or using incognito/private mode

**Comment by TheSgrash** [comment]
I tried to restart multiple times... they just don't load... I gave up for the moment... I'll try in few days and let you know.. thanks

**Comment by vigonotion** [comment]
I'm sorry but I can't reproduce the problem, I use Firefox myself without problems. Without a working reproduction, I cannot help :/
