### ISSUE TITLE
Non functional

### ISSUE THREAD

**Issue by KJThaDon** [vigonotion/hass-simpleicons#247]
This integration is not functional. Do you have any update?

Thank you

**Comment by jvcsw** [comment]
Same here, I follow all guide steps and any icon appears.

HA 2023.11.3

**Comment by 19power97** [comment]
@KJThaDon #240 also suggests adding the si.js to your dashboard resources. In the UI of home assistant, its listed as Manage resources under the three dots on the upper right hand corner while editing any dashboard. Paste this URL when you click add resource `/config/custom_components/simpleicons/data/si.js`. Restart Home Assistant and refresh your browser should do the trick.

I this is what I did after following the Readme.
