### ISSUE TITLE
si:crayon do not work

### ISSUE THREAD

**Issue by mrgrlscz** [vigonotion/hass-simpleicons#248]
Hi, simpleicon is OK on my system (i.e. si:facebook is OK), but this icon do not work:
si:crayon

**Comment by koenkv** [comment]
I have the same problem with 
si:fireflyiii
si:paperlessngx
si:qnap

**Comment by GerdRuetten** [comment]
do you use it under home assistant as hacs-addon?

If so, you must change the requirements to the latest version from SI ... at this time 7.20.0 in the manifest.json

**Comment by mrgrlscz** [comment]
Yes I do:
Changing "simpleicons==7.14.0" in manifest.json to 7.20.0 worked for me (si:crayon is OK).
Thank you!

Seems that si:qnap DO NOT WORK.

**Comment by vigonotion** [comment]
the newest version should work: https://github.com/vigonotion/hass-simpleicons/releases/tag/v2.3.0
