### ISSUE TITLE
Publish release

### ISSUE THREAD

**Issue by LazyTarget** [vigonotion/hass-simpleicons#31]
I see that the master branch is much more updated than the latest release
Could you build a new release and push so that it appears in HACS

The current release is 1.4.0 which uses Simple Icons ^2.19.0
Where as they deployed 3.4.0 which is also referenced in your master branch (since 4 days ago)

**Comment by vigonotion** [comment]
I published a new release now. I'm gonna add automated releases in the future, but if I forget to release a new version again feel free to comment under this issue again

**Comment by LazyTarget** [comment]
Hi! Not sure if Simple Icons was updated correctly

I can't seem to get `si:philipshue` to work which was introduced in 3.3.0
https://github.com/simple-icons/simple-icons/releases

**Comment by vigonotion** [comment]
Please update to hass-simpleicons 1.6.0, I fixed it now:

![grafik](https://user-images.githubusercontent.com/1506970/90369306-da7d7900-e06b-11ea-9e4a-8d46dcbe5f09.png)

**Comment by LazyTarget** [comment]
Now it works :)
Thanks a lot!
