### ISSUE TITLE
Configuration via YAML does not import the module

### ISSUE THREAD

**Issue by jamieshaw** [vigonotion/hass-simpleicons#6]
Following the instructions in the documentation, adding `simpleicons:` to my configuration.yaml does not load the custom_component.

Note: It does work when loading through the integrations UI, and is correctly parsed by the `check_config` script.

---

For reference, this is defined in a YAML that is loaded as part of a `package` via an `!include` reference.

**configuration.yaml**
```yaml
packages: !include_dir_merge_named config/components/
```

**config/components/frontend.yaml**
```yaml
package_frontend:
    simpleicons: ~
```

**Comment by vigonotion** [comment]
Fixed by c427340. There is a new version v1.0.3, which includes this fix. Please let me know if it works for you and reopen this issue if it doesn't
