### ISSUE TITLE
installed via hacs but cant add integration?

### ISSUE THREAD

**Issue by GotNoMana** [vigonotion/hass-simpleicons#60]
fucked if i know whats going on aye

**Comment by vigonotion** [comment]
Can you please describe what you tried already?
Please try restarting Home Assistant and reloading the browser without cache.

**Comment by GotNoMana** [comment]
Legendary -----> clearing cache fixed the issues
> Can you please describe what you tried already?
> Please try restarting Home Assistant and ----->"reloading the browser without cache"<------

**Comment by GotNoMana** [comment]
thankyou, vigonotion.
im going to add this manually I just thought id show u incase you might to add it to the repository?
https://imgur.com/iHQjQyA

**Comment by vigonotion** [comment]
The HACS integration is just a wrapper around https://simpleicons.org/ which I am not affiliated with. If you have icon requests request them there, though they only include logos from famous brands
