### ISSUE TITLE
icons don't load

### ISSUE THREAD

**Issue by Jens-Wymeersch** [vigonotion/hass-simpleicons#66]
@vigonotion I think the simple icons are amazing and would love to use them within home assistant. But I suppose because of the latest changes the icons don't load anymore. I had the same issue with fontawesome and used the workaround proposed by @carlos-sarmiento (https://github.com/carlos-sarmiento/ha-fontawesome) which made it work. 
Anything can be done here ?

**Comment by carlos-sarmiento** [comment]
@Jens-Wymeersch just as an FYI, you can use my project to generate a file compatible with HA for simpleicons. I've just updated the configuration to support it.

**Comment by Jens-Wymeersch** [comment]
@carlos-sarmiento I hoped this was the answer. Now the question is how do i get the full set downloaded. Not clear out of the documentation. Can you please advice ?

**Comment by vigonotion** [comment]
See this issue: https://github.com/vigonotion/hass-simpleicons/issues/35
