### ISSUE TITLE
Incorrect URL

### ISSUE THREAD

**Issue by NickolaosC** [vigonotion/hass-simpleicons#7]
In the latest version of the HACS the first link to simpleicons is incorrect

hass-simpleicons
hacs_badge

Use free icons from the simpleicons set in Home Assistant.

The URL points to 
https://simpleicons.com/
instead of 
https://simpleicons.org/

**Comment by vigonotion** [comment]
Thanks, this bug has already been fixed by 122ee69805de93f0ad6ea3b15cd499e003266ce3.
I'm gonna build a new version with simpleicons 2.10.0 today, and then the link should also be fixed in HACS.
