### ISSUE TITLE
V1.11.0 cannot be added as integration

### ISSUE THREAD

**Issue by Kugelfang666** [vigonotion/hass-simpleicons#72]
I just updated from 1.10 to 1.11. At startup of Home Assistant I got an error message that this integration could not be initialize. I deleted the integration in the menu and tried to re add it but while I can find it in the menu I cannot add it. 

Rolling back to 1.10 immediately solves this issue and the add-on works as expected.

HA: latest version
Intel NUC

```
Logger: homeassistant.setup
Source: setup.py:138 
First occurred: 5:15:45 PM (1 occurrences) 
Last logged: 5:15:45 PM

Setup failed for simpleicons: Unable to import component: No module named 'custom_components.simpleicons.custom_component_server
```

**Comment by vigonotion** [comment]
Thanks for reporting that! I fixed it now and it works locally for me. Can you try v1.11.1? If it doesn't work, you can re-open this issue.

**Comment by Kugelfang666** [comment]
Adding the integration works in 1.11.1 now. However icons are not displayed in Lovelace.... for instance 

icon: 'is:bmw' 

leaves the icon blank

**Comment by vigonotion** [comment]
Did you really use 'is:bmw'? It should be 'si:bmw'.
Otherwise, can you try reloading the page without cache?

**Comment by Kugelfang666** [comment]
I’m using si:XXX sorry was a type. Still icons are missing consistent on all devices (Mac, iPad, iPhone...O) strange. Will try to empty the cache on my Mac an see if it fixes the issue

**Comment by Kugelfang666** [comment]
Ok emptying cache did the trick, this can be closed
