### ISSUE TITLE
No 'version' key in the manifest

### ISSUE THREAD

**Issue by wklink** [vigonotion/hass-simpleicons#95]
https://www.home-assistant.io/blog/2021/03/03/release-20213/#breaking-changes

Custom integrations now require a version key in their manifest file, this also means that all custom integrations now require a manifest file.

```
No 'version' key in the manifest file for custom integration 'simpleicons'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'simpleicons'
```

**Comment by vigonotion** [comment]
Thank you, it's fixed in `v1.13.2`.
